language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
    - codeception
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
matrix:
  include:
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=4.7
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=trunk
install:
  - npm install grunt-cli -g
script:
  - cd build/grunt && npm run install
  - cd build/grunt && grunt build
  - phantomjs --webdriver=4444
  - php vendor/bin/codecept run
